# Generated by Django 3.1.7 on 2021-04-08 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0002_optional_team_captain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="player",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="gaming.player",
            ),
        ),
    ]
